### ISSUE TITLE
DbUpdateConcurrencyException during update

### ISSUE THREAD

**Issue by abircannet** [ardalis/Specification#297]
Contact and ContactDetail entities are used for the one-to-many related database model. Since the Contact entity is Aggregate root, the Contact entity is used to create the ContactDetail record. (like the basket and basketitem object in the eshoponweb application).
The problem is that I am encountering DbUpdateConcurrencyException in _repository.UpdateAsync(contact) code.

Thank you in advance for your help on the subject.

`var contact = await _contactRepository.FirstOrDefaultAsync(new GetContactWithDetailsByContactIdSpec(contactId));

contact.AddDetail(contactDetail); 

await _contactRepository.UpdateAsync(contact); 

return contactDetail;
`

**Comment by ardalis** [comment]
Can you show more code? That all looks fine. Is there a stack trace? What version of EF, etc. are you using?

**Comment by abircannet** [comment]
Thank you for response @ardalis . This is  repository link https://github.com/abircannet/PhoneBookApp/tree/Development

**Comment by abircannet** [comment]
Sorry for being late.

 Exception stack trace:

`   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.<ConsumeAsync>d__8.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__29.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.<ExecuteAsync>d__9.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__103.MoveNext()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<SaveChangesAsync>d__107.MoveNext()
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__60.MoveNext()
   at Microsoft.EntityFrameworkCore.DbContext.<SaveChangesAsync>d__60.MoveNext()
   at Ardalis.Specification.EntityFrameworkCore.RepositoryBase`1.<SaveChangesAsync>d__10.MoveNext()
   at Ardalis.Specification.EntityFrameworkCore.RepositoryBase`1.<UpdateAsync>d__6.MoveNext()
   at Cdr.ContactMicroservice.Domain.Services.ContactService.<AddDetailToContactAsync>d__3.MoveNext() in C:\Users\abirc\Desktop\Rise\SolutionRepo\PhoneBookApp\PhoneBookSolution\ContactMicroservice\Cdr.ContactMicroservice.Domain\Services\ContactService.cs:line 37`

I try EF Core Version 6.0.8 and 6.0.10

**Comment by abircannet** [comment]
When I test with MSSQL and SQLite, there is no problem.

**Comment by ardalis** [comment]
Can you try doing the same query with your DbContext but without using Specification? I'm assuming if you send the same set of expressions directly to the DbContext you will get the same exception. @fiseni can send you some more info.

**Comment by fiseni** [comment]
@abircannet did you manage to test directly with DbContext without specs and repository?
Closing the issue due to inactivity. Feel free to re-open it if you need further assistance.
