### ISSUE TITLE
Object reference not set to an instance of an object error.

### ISSUE THREAD

**Issue by commodus** [ardalis/Specification#405]
Hello,

I’m using version 8.0.0 of the Ardalis.Specification library. When the CreateBrandRequest event is triggered as shown in the screenshot, the FluentValidation implemented CreateBrandRequestValidator method runs. The IReadRepository<Brand> _repository is injected and is not null, and the name parameter is not null, but when I call the repository method with the BrandByNameSpec parameter on line 27, I get a System.NullReferenceException: 'Object reference not set to an instance of an object.' error on this line. I would appreciate your help. Thank you.

![image](https://github.com/user-attachments/assets/44be00f8-f65a-4c3b-83dd-e8831753e936)

Stack Trace :
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Ardalis.Specification.EntityFrameworkCore.RepositoryBase`1.<FirstOrDefaultAsync>d__15.MoveNext()
   at JTR.WebApi.Application.Catalog.Brands.CreateBrandRequestValidator.<>c__DisplayClass1_0.<<-ctor>b__1>d.MoveNext() 
   
![image](https://github.com/user-attachments/assets/2232cfae-fe19-41a0-b3c8-a87065aef171)

**Comment by fiseni** [comment]
@commodus Sorry, we've missed this issue somehow.
Are you still facing the issue? Can you please post a reproducible example?

**Comment by fiseni** [comment]
Closing this one. Feel free to reopen the issue if you're still facing issues.
